// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RPCMethod } from "./RPCMethod";

export interface RPCRequest { user_id: string, token: string, method: RPCMethod, protocol: number, }